environment <- 'ENVIRONMENT' |> Sys.getenv()

expect.exist      <- \(actual) actual |> is.null() |> expect_equal(FALSE) 
expect.true       <- \(actual) actual |> expect_equal(TRUE)
expect.false      <- \(actual) actual |> expect_equal(FALSE)
expect.equal      <- \(actual, expected) actual |> expect_equal(expected)
expect.function   <- \(actual) actual |> is.function() |> expect_equal(TRUE)
expect.vector     <- \(actual) actual |> is.vector() |> expect_equal(TRUE)
expect.character  <- \(actual) actual |> is.character() |> expect_equal(TRUE)
expect.numeric    <- \(actual) actual |> is.numeric() |> expect_equal(TRUE)
expect.integer    <- \(actual) actual |> is.integer() |> expect_equal(TRUE)
expect.logical    <- \(actual) actual |> is.logical() |> expect_equal(TRUE)
expect.factor     <- \(actual) actual |> is.factor() |> expect_equal(TRUE)
expect.matrix     <- \(actual) actual |> is.matrix() |> expect_equal(TRUE)
expect.data.frame <- \(actual) actual |> is.data.frame() |> expect_equal(TRUE)
expect.list       <- \(actual) actual |> is.list() |> expect_equal(TRUE)
expect.no.error   <- \(actual) actual |> expect_no_error()
expect.error      <- \(actual, error = NULL) actual |> expect_error(error)
expect.warning    <- \(actual, warning = NULL) actual |> expect_warning(warning)
expect.rows       <- \(actual, rows) actual |> nrow() |> expect_equal(rows)
expect.not.na     <- \(actual) actual |> is.na() |> expect_equal(FALSE)
expect.equal.data <- \(actual, expected) actual |> all.equal(expected, check.attributes = FALSE) |> isTRUE() |> expect_equal(TRUE)